# Generated by Django 4.2.4 on 2023-08-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_amount_of_orders_product_link_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount_of_orders',
        ),
    ]
